### ISSUE TITLE
Using arguments in the REPL

### ISSUE THREAD

**Issue by tomchor** [carlobaldassi/ArgParse.jl#101]
Sorry if this question is naive, but I'm new to Julia and I couldn't find anything in the docs or online.

I set-up my arguments as such:

```julia
function parse_command_line_arguments()
    settings = ArgParseSettings()

    @add_arg_table! settings begin

        "--factor"
            help = "Factor to divide Nh and Nz for"
            default = 16
            arg_type = Int

        "--arch"
            help = "CPU or GPU"
            default = :CPU
            arg_type = Symbol
    end

    return parse_args(settings)
end
```

And this works fine when start my script as `julia mwe.jl`. However, 95% of the times, I'm doing development on the script and I'm actually loading it into the REPL as `include("mwe.jl")`. 

Is there any way of making use of the ArgParse arguments when doing that? Something like `include("mwe.jl --factor=1")`?

**Comment by carlobaldassi** [comment]
The only thing I can think of is to overwrite the `ARGS` constant before calling `include`. Something like
```julia
julia> empty!(ARGS); append!(ARGS, ["--factor=1", "--arch=:CPU"]);

julia> include("mwe.jl") # assuming this calls parse_command_line_arguments
```

**Comment by ali-ramadhan** [comment]
Thanks for the suggestion @carlobaldassi! It's been working out great.

I was wondering if it's possible to do this for an argument that takes multiple values like `--size 10 25 50`? I think it complains about `append!(ARGS, ["--size 10 25 50"])` and `append!(ARGS, ["--size=10 25 50"])`.

**Comment by carlobaldassi** [comment]
@ali-ramadhan just do `append!(ARGS, ["--size", "10", "25", "50"])`
In general you can have a file called `args.jl` which contains the single line `println(ARGS)` and then in the terminal try things like
```
$ julia args.jl --size 10 25 50`
```
In this way you can see the format of how things are passed to julia and you can emulate that.
