### ISSUE TITLE
How do I store constant (as opposed to global)?

### ISSUE THREAD

**Issue by bk322** [carlobaldassi/ArgParse.jl#11]
Hi,
Is there a way to store arg as `const x = 123`, as opposed to store it as `global x = 123`? I read the docs, it mention `constant` but it is always connected with a value stored if nothing were passed. The point is I read computation values from command line, and I want them to be stored as `const` so to speed up my computation.

**Comment by carlobaldassi** [comment]
I really don't think there's a way to do this from ArgParse. The `constant` mentioned in ArgParse is unrelated to julia's `const`.
The only thing I can come up to is writing the values in a file and the use `include`, i.e. something like this:

```julia
module ParserFile
using ArgParse

function main(args)
    s = ArgParseSettings(#= ... =#)
    @add_arg_table s begin
        "-x"
    end
    parsed_args = parse_args(s)
    open("parsed_args.jl", "w") do f
        println(f, "const x=", parsed_args["x"])
    end
end

main(ARGS)

include("parsed_args.jl")

function dowork()
    # here we can do something with x...
    println(x)
end

dowork()

end
```

Of course you'd want to generate a unique name for the `"parsed_args.jl"` file, and then delete it, etc. I hope this helps.
