### ISSUE TITLE
Insert line break in wrapped text (e.g., the "epilog")

### ISSUE THREAD

**Issue by simonp0420** [carlobaldassi/ArgParse.jl#12]
I would like to be able to insert a line break in the epilog to provide visual separation for different examples.  Question first raised at  https://groups.google.com/forum/#!topic/julia-users/ZvJmdwJmuwo

Perhaps you could provide support for Markdown in your documentation strings?  Something like
 
```julia
s.epilog = md""" A Markdown string"""
```

Thanks for the great package that I make heavy use of!

**Comment by carlobaldassi** [comment]
The Markdown idea is really interesting. I'll have to explore that in more detail.

I wonder if it's overkill for what we want to achieve here though. One thing I was thinking was very simply to allow forcing newlines in the description and the epilog by writing two of them in a row.

Would that work for you? Do you think you'd have a use for more features which Markdown could provide?

BTW the two things don't exclude each other.

**Comment by simonp0420** [comment]
Certainly being able to specify newlines would be a big help and your approach would definitely work for me.  Ideally, I would like the help material provided by the -h option to be the same as in the user manual, which is created with Markdown.  So the section headers would be appropriately highlighted, etc., presumably using Markdown.jl.  Not necessary, but it would be very nice and I would make use of it.  But whatever you have time for would be great, even just the line breaks.

**Comment by carlobaldassi** [comment]
I fixed it the easy way for the time being. I still consider markdown as a good ides, but I'm not sure how much work it would require to make it fit.

(In case someone's interested, PRs would be welcome of course.)

Anyway, an example of how to achieve some rudimentary formatting control on epilogs is now [here](https://github.com/carlobaldassi/ArgParse.jl/blob/810240fb748eda19fee13b61b781c4374d882afc/examples/argparse_example4.jl#L43).

I'll now tag a new version.

**Comment by simonp0420** [comment]
Thanks!
