### ISSUE TITLE
How to separate julia options?

### ISSUE THREAD

**Issue by sptrakesh** [carlobaldassi/ArgParse.jl#120]
Julia itself supports a variety of options (such as history file, optimization level etc).  How do I ignore these options when someone calls my script?  I have declared those that my script needs, but if a user passes other julia options, then the parser reports an error about excess arguments.

May be related to [82](https://github.com/carlobaldassi/ArgParse.jl/issues/82).

**Comment by carlobaldassi** [comment]
This should work:
```
julia --threads 4 -- argparse_example1.jl -o "option" -- argument
```
