### ISSUE TITLE
Parametrize lc_len_limit

### ISSUE THREAD

**Issue by ahojukka5** [carlobaldassi/ArgParse.jl#129]
https://github.com/carlobaldassi/ArgParse.jl/blob/master/src/parsing.jl#L140

lc_len_limit is hard coded to 24 which is not necessary enough if optional argument lengths are long enough (the result will not look good). It would be good to parametrize this so that it can be increased if needed.

**Comment by carlobaldassi** [comment]
That setting refers to the indentation of lines after the first in the "usage" output. Like this one:
```
usage: argparse_example3.jl [--opt1 [OPT1]] [-k] [--version] [-h]
                        arg1 arg1 [arg2...]
```

Here the `arg1 ...` part is indented by 24 spaces.

Is this what you were referring to? Or is it rather the overall width of the usage/help display (which is set to 70 at the moment)? I think making that customizable would be more useful.
