### ISSUE TITLE
Options dependency?

### ISSUE THREAD

**Issue by Keno** [carlobaldassi/ArgParse.jl#13]
With newer versions of julia, is the Options package still needed or can ArgParse be rewritten to remove the dependency?

**Comment by carlobaldassi** [comment]
Still needed. Well, very useful at least. (If you're referring to keyword argument, they're not enough.) In particular, see [these lines](https://github.com/carlobaldassi/ArgParse.jl/blob/810240fb748eda19fee13b61b781c4374d882afc/src/ArgParse.jl#L636-L652), and especially the first one.
What's the problem anyway?

**Comment by Keno** [comment]
There's no problem, I got a deprecation warning in Options and was surprised that it was still loaded at all by any package, since I thought the core language changes made it obsolete.

**Comment by carlobaldassi** [comment]
Thinking more about it, I could probably reimplement everything with just keyword arguments, but it would be more difficult, somewhat ugly(*), a breaking change, and I don't really see the point.

(*) well it's not like the current code is beauiful...
