### ISSUE TITLE
ArgParse 1.1.5 prints `desc` while precompiling

### ISSUE THREAD

**Issue by bluesmoon** [carlobaldassi/ArgParse.jl#130]
I don't know where this is coming from, but when I precompile my project in Julia 1.10 with ArgParse 1.1.5, I get this message:

```
  1 dependency had output during precompilation:
┌ ArgParse
│  desc
└  
```

**Comment by giordano** [comment]
Culprit is https://github.com/carlobaldassi/ArgParse.jl/blob/682fe1b67839f45ae2d00f333ca1d6d60c491464/src/common.jl#L10 called at https://github.com/carlobaldassi/ArgParse.jl/blob/682fe1b67839f45ae2d00f333ca1d6d60c491464/src/settings.jl#L872
