### ISSUE TITLE
Support for custom types

### ISSUE THREAD

**Issue by c42f** [carlobaldassi/ArgParse.jl#17]
I have a custom type `LogConfig` which I'd like to add as an ArgParse argument.  By default, using `arg_type=LogConfig` causes "invalid argument: error (must be of type CommandLine.LogConfig)".  I've managed to get things working by overloading `ArgParse.parse_item` with my custom type, but it's not clear from the docs that this is the right thing.

Here's a cut down example of what I'm trying to do.  Run as, for example, `julia test_custom_type.jl --loglevel warning`.

```julia
using Logging
using ArgParse

type LogConfig
    level::Logging.LogLevel
end

function LogConfig(logconf::String)
    if     logconf == "error"   return LogConfig(Logging.ERROR)
    elseif logconf == "warning" return LogConfig(Logging.WARNING)
    elseif logconf == "info"    return LogConfig(Logging.INFO)
    elseif logconf == "debug"   return LogConfig(Logging.DEBUG)
    else                        return LogConfig(Logging.INFO) # default
    end
end

ArgParse.parse_item(::Type{LogConfig}, logconf::String) = LogConfig(logconf)

settings = ArgParseSettings()
@add_arg_table settings begin
    "--loglevel"
        help = "Logging verbosity none|error|warning|info|debug [info]"
        arg_type = LogConfig
        default = LogConfig("info")
end

args = parse_args(settings)

show(args["loglevel"])
println()
```

Related, I noticed that `parse_item(it_type::Type, x::String)` calls `parse()` internally as `eval(parse(x)[1])`.  After squinting at this for a while I still don't understand exactly what it's trying to achieve with the indexing, but I do wonder whether it implies arbitrary code execution during command line parsing, which seems like a bad thing from a security point of view.

**Comment by c42f** [comment]
This is with a julia 0.4 by the way (0.4.0-pre+7155).  Maybe the `eval(parse(x)[1])` is just a hangover from an earlier version of the `parse()` API which happens to still work?  I did a little digging, but `parse()` seems stable at least back until 0.2.

**Comment by sjkelly** [comment]
Hi @c42f I am currently working on modernizing this package. I think you are correct that the `eval` call does not seem safe. It seems like you want `arg_type` to be a `call`. The `arg_type` currently works at the parser level, i.e. literal `typeof(parse("1.")) => Float64`. This means `arg_type` is stuck with the types the parser know about. We could do this simply on 0.4 with `call(arg_type, parse("foo"))` which would dispatch to `arg_type(::Symbol)` (which is better on memory and safer).

**Comment by c42f** [comment]
On further thought, I don't think we should be going through the julia parser at all for this.  I'd expect either that a custom type simply needs a method to convert a string (as passed by the user on the command line) to the type.

By default, it makes sense to me that a constructor `MyCustomType(::String)` gets called.  If the user wanted to override that (for example, to use a custom type in some module not controlled by them), `ArgParse` should define some public method which can be overridden instead of the constructor.  Just making something like `parse_item` part of the public interface would serve quite well I think.

**Comment by JohnHBrock** [comment]
Did that `eval(parse(x)[1])` line ever work? Is there a good reason not to change that to `eval(parse(x))`?

**Comment by carlobaldassi** [comment]
Yes it did work, but it was written before julia 0.1 I think. And yes it has always been a security concern (it's also stated in the manual somewhere) which I had been want to change for ages.
Sorry for the delay in the answers to this and other issues, I'll get to it in the next few days, as soon as I can.

**Comment by carlobaldassi** [comment]
Please all interested folks have a look at this branch I just pushed: https://github.com/carlobaldassi/ArgParse.jl/tree/noopt which should fix this issue (besides removing the dependency on Options).
I intend to merge it and bump ArgParse's minor version, since it changes the API.
So now it's the time for criticisms...

**Comment by c42f** [comment]
Thanks, this basically addresses the issue here and I think it's a nice compromise between security and hackability.
