### ISSUE TITLE
Deprecation warnings with Julia 0.4.0-rc1

### ISSUE THREAD

**Issue by r5r3** [carlobaldassi/ArgParse.jl#21]
Using ArgParse with Julia 0.4.0 is producing the following warnings:
WARNING: ntuple(n::Integer,f::Function) is deprecated, use ntuple(f,n) instead.
WARNING: `require` is deprecated, use `using` or `import` instead

**Comment by carlobaldassi** [comment]
Closed by #18.

**Comment by r5r3** [comment]
Thanks for the fast fix! 

There is still a warning issued:
WARNING: requiring "Options" did not define a corresponding module.
