### ISSUE TITLE
Support arguments starting with hypens

### ISSUE THREAD

**Issue by omus** [carlobaldassi/ArgParse.jl#26]
Although it is unusual sometimes positional arguments can start with a hypen. I'll demonstrate below using the file `example.jl`:
```julia
using ArgParse
settings = ArgParseSettings()

@add_arg_table settings begin
    "--opt"
        default = ""
    "arg"
        required = true
end

parsed_args = parse_args(ARGS, settings)
println(parsed_args)
```

When using this simple Julia file I can run it as follows which produces the expected result:
```bash
$ julia example.jl -a
unrecognized option -a
usage: example.jl [--opt OPT] arg
```

However `-a` should be treated as a positional argument if it occurs after a `--`:
```bash
$ julia example.jl -- -a
unrecognized option -a
usage: example.jl [--opt OPT] arg
```
But unfortunately this is not the behaviour. For reference see the Python argparse documentation section ["Arguments containing -"](https://docs.python.org/3/library/argparse.html#arguments-containing)

**Comment by carlobaldassi** [comment]
Yes, this was supposed to work. I'll investigate.

**Comment by omus** [comment]
Thanks!

**Comment by carlobaldassi** [comment]
Looks like the `--` is eaten up by julia parsing the command line. You can check that by printing `ARGS` in your example file before even trying to parse it. I'll see if something can be done about that.

**Comment by carlobaldassi** [comment]
This was fixed in https://github.com/JuliaLang/julia/pull/17371. It will hopefully be backported to 0.4 too.
