### ISSUE TITLE
types and metavars when nargs > 1

### ISSUE THREAD

**Issue by samkohn** [carlobaldassi/ArgParse.jl#29]
I'd like to be able to specify a different type and/or metavar for each argument in a mulit-argument option. Here's a use case that demonstrates my request:

``` julia
@add_arg_table s begin
    "--point"
       nargs = 3
       metavar = ["X", "Y", "LABEL"]
       arg_type = [Float64, Float64, AbstractString]
end
```

The best I can do is to put `metavar = "X"`, which results in help messages of `--point X X`, which is not what I want. Further, `metavar = "X_THEN_Y"` doesn't work either, since it results in `--point X_THEN_Y X_THEN_Y`.

Of course, this problem could be solved by adding more arguments, but my program already has a bunch of other arguments and I don't want this particular feature to take up 3 more.

If there's some support for this idea out there, I may be able to implement it myself within a few weeks.

**Comment by carlobaldassi** [comment]
Sorry, I had totally missed this. If you want to submit a pull request you're more than welcome.

**Comment by samkohn** [comment]
I'm running into an issue using the `check_type` function [on line 748](https://github.com/carlobaldassi/ArgParse.jl/blob/master/src/ArgParse.jl#L748) since `Vector{ASCIIString}` is not a subset of `Vector{AbstractString}` (i.e. `isa(ASCIIString["a", "b"], Vector{AbstractString})` returns `false`).

I'd like to just not call that function—if `metavar` is the wrong type, it will show up later when `check_metavar` is called. Is there a particular reason that I shouldn't just remove that line?

**Comment by carlobaldassi** [comment]
The reason for that function is that I prefer catching obvious mistakes early and giving a clear error message if possible, rather than relying on no-method errors.

I think you could probably just change the line with something like this

```julia
isa(metavar, AbstractString) ||
    (isa(metavar, Vector) && all(x->isa(x, AbstractString), metavar)) ||
    error("...")
```

**Comment by samkohn** [comment]
That's a sensible reason. I'll work from there. Thanks for the suggestion.
