### ISSUE TITLE
not exiting Julia after help

### ISSUE THREAD

**Issue by denizyuret** [carlobaldassi/ArgParse.jl#41]
Is it possible not to exit Julia after displaying the help string?  I saw a keyword argument in the function to this effect but there is no way to call it with the non-default setting.  I use the debug_handler for not quitting after errors.  This is useful e.g. while debugging or in an IJulia notebook.

**Comment by stefan911** [comment]
Perhaps adding a no_exit_handler that: prints to stderr, returns default values, and doesn't call exit().   This would make this much more useful inside the REPL or notebook.

**Comment by stefan911** [comment]
Thanks for ArgParse, example code for in REPL taming of exit on error/help:
```
    s = ArgParseSettings()
    if Base.isinteractive() 
        function repl_handler(settings::ArgParseSettings, err, err_code::Int = 1)
            println(stderr, err.text)
            println(stderr, usage_string(settings))
            throw(err)
        end
        s.exit_after_help = false
        s.exc_handler = repl_handler
    end
```
