### ISSUE TITLE
ArgParse: fetch failed to get commit 7e0f30e78a

### ISSUE THREAD

**Issue by nbonacker** [carlobaldassi/ArgParse.jl#46]
I got the error message

> ERROR: ArgParse: fetch failed to get commit 7e0f30e78a, please file an issue at https://github.com/carlobaldassi/ArgParse.jl/issues
>  in fetch(::Base.LibGit2.GitRepo, ::String, ::String) at ./pkg/write.jl:25
>  in #3 at ./pkg/write.jl:53 [inlined]
>  in with(::Base.Pkg.Write.##3#4{String,String}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
>  in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:537
>  in update(::String, ::Set{String}) at ./pkg/entry.jl:458
>  in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at ./pkg/dir.jl:31
>  in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at ./file.jl:59
>  in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib:?
>  in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
>  in update() at ./pkg/pkg.jl:210
> 

while upgrading ArgParse from v0.4.0 to v0.5.0.

My first issue. Thanks, a lot. Niklas

**Comment by carlobaldassi** [comment]
The commit is definitely there. If this is the only package on which you see such error, I suspect a temporary github problem. Can you try again, perhaps in a while?

**Comment by nbonacker** [comment]
With Julia 0.6.0. there is no problem. Everything is working fine. The error remains for Julia 0.5.0.

Thanks. Niklas

**Comment by carlobaldassi** [comment]
This is very weird, I have never seen anything like it.
Maybe some kind of issue with your local .julia directory? You could try to go into `~/.julia/v0.5/ArgParse` and see if `git status` tells you anything out of the ordinary.

**Comment by nbonacker** [comment]
Great. I am on branch master again. Sorry.
```
mac20:ArgParse bonacker$ git status
Not currently on any branch.
nothing to commit, working tree clean
mac20:ArgParse bonacker$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
```
Everything works fine. Going on with statistical mechanics. Thanks. Niclas

**Comment by carlobaldassi** [comment]
I'm glad it's working again, although the "not currently in any branch" previous status was in fact the normal working condition for a Julia package. Oh well.
