### ISSUE TITLE
Feature request: Add mutually exclusive options

### ISSUE THREAD

**Issue by lucatrv** [carlobaldassi/ArgParse.jl#58]
See Python's `argparse` method `add_mutually_exclusive_group()`:  [https://docs.python.org/3.6/howto/argparse.html#conflicting-options](https://docs.python.org/3.6/howto/argparse.html#conflicting-options)

**Comment by bjarthur** [comment]
dup of https://github.com/carlobaldassi/ArgParse.jl/issues/25
