### ISSUE TITLE
Add support for subcommands

### ISSUE THREAD

**Issue by kdheepak** [carlobaldassi/ArgParse.jl#62]
Hi, I was wondering how much effort it would be to add support for subcommands (similar to git)? That way we'd be able to run both of the following from the same file.

```bash
julia filename.jl convert filename --from format1 --to format2
# OR
julia filename.jl validate filename
```

Thoughts?

**Comment by carlobaldassi** [comment]
This is already possible:
[docs](http://carlobaldassi.github.io/ArgParse.jl/latest/arg_table.html#Commands-1)
[example](https://github.com/carlobaldassi/ArgParse.jl/blob/master/examples/argparse_example6.jl)

**Comment by kdheepak** [comment]
I should have just read the docs more carefully! Thanks!
