### ISSUE TITLE
Add custom error message if range_tester fails?

### ISSUE THREAD

**Issue by endrebak** [carlobaldassi/ArgParse.jl#66]
The following output for a missing input file is not super helpful:

```
out of range input for --chip: examples/test3.bed
```

Would be better with `file not found: examples/test3.bed`.

**Comment by endrebak** [comment]
Also, for my `--outfile` arg I have this range_tester function:

```julia
function create_path_or_fail(x)

    # will raise SystemError if trying to create a file which
    # we are not allowed to create. e.g. ("/usr/hello.txt")
    result = mkpath(dirname(x))
    open(x, "w+")

    return true
end
```

The error which is raised is super helpful, but it does not propagate to the script, it just says

```
out of range input for --outfile: /usr/dest.txt
```

but the original error is much more understandable:

`ERROR: SystemError: opening file /usr/hi.txt: Operation not permitted`

**Comment by carlobaldassi** [comment]
My idea for range testers was that they would be convenient mostly for numeric inputs. or to check strings etc. For your situation, where the original error message is actually already clear, it seems that the easiest thing to do would be to just test the arguments after the parsing.

Or is it still somehow more convenient to run the test from ArgParse?

(Disclaimer: I'm all for customization, but the library is already pretty complicated as is, I'd rather be sure that the use cases justify the added complexity.)

**Comment by endrebak** [comment]
No, I guess you could have a `check_args` afterwards. It is just unlike other APIs I have used that the kinds of checks are restricted to certain types :)
