### ISSUE TITLE
An argument with internal spaces is parsed as two arguments

### ISSUE THREAD

**Issue by fjarri** [carlobaldassi/ArgParse.jl#73]
The code: 

    using ArgParse

    s = ArgParseSettings()
    @add_arg_table s begin
        "--opt"
            help = "an option with an argument"
    end

    parsed_args = parse_args(ARGS, s)
    println(parsed_args)

When given a (quoted) argument with a space inside, returns an error:

    $ julia t.jl --opt "test test2"
    too many arguments
    usage: t.jl [--opt OPT]

**Comment by carlobaldassi** [comment]
I can't reproduce, I tried julia 0.6, 0.7 and 1.0. I'm on linux using bash:

```
$ julia-1.0 argparse_example1.jl --opt1 "test test2"
Parsed args:
  arg1  =>  nothing
  opt1  =>  "test test2"
  opt2  =>  nothing
```

What's your julia version/OS/terminal?

**Comment by fjarri** [comment]
Macos 10.13.6, Julia 1.0, fish and bash (happens in both). 

It seems that it is a Julia quirk though, not related to ArgParse. I get the same parsing result (`test1` and `test2` separate) if I just `println(ARGS)` in Julia, but in Python they stay together as one argument.

**Comment by carlobaldassi** [comment]
Possibly a problem specific to MacOS then. You should probably see if there's an issue open about this on julia, or open one yourself if not.

**Comment by fjarri** [comment]
Turned out it was my mistake, I called julia via a bash script with `$@` unquoted.
