### ISSUE TITLE
Idea to update `parse_item`?

### ISSUE THREAD

**Issue by magerton** [carlobaldassi/ArgParse.jl#86]
I'm using the following overloads for `parse_item`, which allow me to pass in unevaluated expressions like `log(2)` or `3*6^2`. They seem to be a bit more flexible that what's currently in master, and allow me to pass in custom types a bit more easily. I'm not sure if there are security or other performance implications, however, compared to what's currently in use.

https://github.com/carlobaldassi/ArgParse.jl/blob/37e91f4cb8104afdc9d61535529f8a31f9937dda/src/ArgParse.jl#L1513-L1515

Possible change:

```julia
ArgParse.parse_item(::Type{Vector{T}}, x::AbstractString) where {T} =
    eval(parse(x))::Vector{T}

ArgParse.parse_item(::Type{T}, x::AbstractString) where {T<:Real} =
    eval(parse(x))::T
```

**Comment by carlobaldassi** [comment]
Yes, this is disabled for security reasons. But you can add the option `eval_arg=true` when specifying an option or argument in `@add_arg_table` (see the docs [here](https://carlobaldassi.github.io/ArgParse.jl/stable/arg_table.html#Argument-entry-settings-1)).

**Comment by magerton** [comment]
Thanks, @carlobaldassi!
